name: per-commit-checks

on: push

jobs:
  checks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5

      - run: uv.run stubgen
      - run: uv run fl --ci
      - run: uv build

      - uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: dist/*.whl